ALTER TABLE usuarios
ALTER COLUMN id SET NOT NULL,
ALTER id ADD GENERATED ALWAYS AS IDENTITY,
ADD CONSTRAINT unique_usuario_id UNIQUE (id);

ALTER TABLE destinos
ALTER COLUMN id SET NOT NULL,
ALTER id ADD GENERATED ALWAYS AS IDENTITY,
ADD CONSTRAINT unique_destino_id UNIQUE (id);

ALTER TABLE reservas
ALTER COLUMN id SET NOT NULL,
ALTER id ADD GENERATED ALWAYS AS IDENTITY,
ADD CONSTRAINT unique_reserva_id UNIQUE (id);

ALTER TABLE reservas
ADD CONSTRAINT fk_reserva_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id);

ALTER TABLE reservas
ADD CONSTRAINT fk_reserva_destino FOREIGN KEY (id_destino) REFERENCES destinos (id);