ALTER TABLE usuarios
ALTER COLUMN id SET NOT NULL,
ALTER id ADD GENERATED ALWAYS AS IDENTITY,
ADD CONSTRAINT unique_usuario_id UNIQUE (id);

ALTER TABLE destinos
ALTER COLUMN id SET NOT NULL,
ALTER id ADD GENERATED ALWAYS AS IDENTITY,
ADD CONSTRAINT unique_destino_id UNIQUE (id);

ALTER TABLE reservas
ALTER COLUMN id SET NOT NULL,
ALTER id ADD GENERATED ALWAYS AS IDENTITY,
ADD CONSTRAINT unique_reserva_id UNIQUE (id);

ALTER TABLE reservas
DROP CONSTRAINT fk_reserva_usuario,
ADD CONSTRAINT fk_reserva_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON DELETE CASCADE;

ALTER TABLE reservas
DROP CONSTRAINT IF EXISTS fk_reserva_destino,
ADD CONSTRAINT fk_reserva_destino FOREIGN KEY (id_destino) REFERENCES destinos (id) ON DELETE CASCADE;