services:
  postgres:
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=introductionToSQL
    volumes:
      - intro_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=adm@adm.com
      - PGADMIN_DEFAULT_PASSWORD=senha123
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  intro_data:
  pgadmin_data:
    